version: '3'

services:
  django:
    build: .
    container_name: django_hotel
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env.example
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    container_name: pgdb_hotel
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: